"""add_transaction_id_to_orders

Revision ID: a7a9c877d890
Revises: 37322fbbc716
Create Date: 2026-04-08 08:39:44.836952+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7a9c877d890'
down_revision: Union[str, Sequence[str], None] = '37322fbbc716'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('transaction_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_orders_transaction_id'), 'orders', ['transaction_id'], unique=False)
    op.create_foreign_key(None, 'payments', 'orders', ['order_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_index(op.f('ix_orders_transaction_id'), table_name='orders')
    op.drop_column('orders', 'transaction_id')
    # ### end Alembic commands ###
